### ISSUE TITLE
GUI stranky

### ISSUE THREAD

**Issue by Felda01** [TIS2018-FMFI/headis#11]
vytvorit gui v mock-e

**Comment by Felda01** [comment]
- [ ] [GUI template](https://github.com/TIS2018-FMFI/headis/issues/21)

- [ ] [GUI hlavna stranka](https://github.com/TIS2018-FMFI/headis/issues/20)

- [ ] [GUI uzivatel](https://github.com/TIS2018-FMFI/headis/issues/19)

- [ ] [GUI vyzva a zapas](https://github.com/TIS2018-FMFI/headis/issues/18)

- [ ] [GUI rebrickova pyramida a statistiky](https://github.com/TIS2018-FMFI/headis/issues/17)
